package com.travelmantics;


import android.content.Context;
import android.content.Intent;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;

import com.google.firebase.database.ChildEventListener;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.ArrayList;

public class DealsAdapter extends RecyclerView.Adapter<DealsAdapter.DealViewHolder> {
    private FirebaseDatabase mFirebaseDatabase;
    private DatabaseReference mFirebaseReference;
    ArrayList<TravelDeal> mDeals;
    private ChildEventListener mChildEventListener;

    public DealsAdapter(){

        mFirebaseDatabase = FirebaseUtil.mFirebaseDatabase;
        mFirebaseReference =FirebaseUtil.mDatabaseReference;
        mDeals =FirebaseUtil.mDeals;
        mChildEventListener = new ChildEventListener() {

            @Override
            public void onChildAdded(@NonNull DataSnapshot dataSnapshot, @Nullable String s) {
                TravelDeal td = dataSnapshot.getValue(TravelDeal.class);
                Log.d("Deals:", td.getTitle());
                //set the id of the deal to the push Id key that was generated by firebase so we
                //can read it later
                td.setID(dataSnapshot.getKey());
                 mDeals.add(td);
                 notifyItemInserted(mDeals.size()-1);

            }

            @Override
            public void onChildChanged(@NonNull DataSnapshot dataSnapshot, @Nullable String s) {

            }

            @Override
            public void onChildRemoved(@NonNull DataSnapshot dataSnapshot) {

            }

            @Override
            public void onChildMoved(@NonNull DataSnapshot dataSnapshot, @Nullable String s) {

            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        };
        mFirebaseReference.addChildEventListener(mChildEventListener);
    }

    @NonNull
    @Override
    public DealViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        Context context =  parent.getContext();
        View itemView = LayoutInflater.from(context)
                .inflate(R.layout.row_layout,parent, false);

        return new DealViewHolder(itemView);
    }

    @Override
    public void onBindViewHolder(@NonNull DealViewHolder holder, int position) {
        TravelDeal deal = mDeals.get(position);
       holder.bind(deal);
    }

    @Override
    public int getItemCount() {
        return mDeals.size();
    }



    //to describe how to bind the data to a single row
    public class DealViewHolder extends RecyclerView.ViewHolder
        implements View.OnClickListener {

        TextView tvTitle;
        TextView tvDescription;
        TextView tvPrice;

         public DealViewHolder(@NonNull View itemView) {
            super(itemView);
            tvTitle = itemView.findViewById(R.id.txt_title);
            tvDescription = itemView.findViewById(R.id.txt_description);
            tvPrice = itemView.findViewById(R.id.txt_price);
            //set an item click listener on the itemView
             itemView.setOnClickListener(this);
        }


        public void bind(TravelDeal deal){
             tvTitle.setText(deal.getTitle());
             tvDescription.setText(deal.getDescription());
            tvPrice.setText(deal.getPrice());
         }

        @Override
        public void onClick(View view) {
            //get the position of the item clicked
            int position  = getAdapterPosition();
            Log.d("Click:", String.valueOf(position));
            TravelDeal selectedDeal = mDeals.get(position);
            Intent intent = new Intent(view.getContext(),DealActivity.class);
            intent.putExtra("Deal", selectedDeal );
            //we need to call the startActivity method from the context of the current view
            view.getContext().startActivity(intent);
        }
    }
}
