package com.travelmantics;


import android.content.Context;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;

import com.google.firebase.database.ChildEventListener;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.ArrayList;

public class DealsAdapter extends RecyclerView.Adapter<DealsAdapter.DealViewHolder> {
    private FirebaseDatabase mFirebaseDatabase;
    private DatabaseReference mFirebaseReference;
    ArrayList<TravelDeal> deals;
    private ChildEventListener mChildEventListener;

    public DealsAdapter(){
        FirebaseUtil.dbreference("traveldeals");
        mFirebaseDatabase = FirebaseUtil.mFirebaseDatabase;
        mFirebaseReference =FirebaseUtil.mDatabaseReference;
        deals =FirebaseUtil.mDeals;
        mChildEventListener = new ChildEventListener() {

            @Override
            public void onChildAdded(@NonNull DataSnapshot dataSnapshot, @Nullable String s) {
                TravelDeal td = dataSnapshot.getValue(TravelDeal.class);
                Log.d("Deals:", td.getTitle());
                //set the id of the deal to the push Id key that was generated by firebase so we
                //can read it later
                td.setID(dataSnapshot.getKey());
                 deals.add(td);
                 notifyItemInserted(deals.size()-1);

            }

            @Override
            public void onChildChanged(@NonNull DataSnapshot dataSnapshot, @Nullable String s) {

            }

            @Override
            public void onChildRemoved(@NonNull DataSnapshot dataSnapshot) {

            }

            @Override
            public void onChildMoved(@NonNull DataSnapshot dataSnapshot, @Nullable String s) {

            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        };
        mFirebaseReference.addChildEventListener(mChildEventListener);
    }

    @NonNull
    @Override
    public DealViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        Context context =  parent.getContext();
        View itemView = LayoutInflater.from(context)
                .inflate(R.layout.row_layout,parent, false);

        return new DealViewHolder(itemView);
    }

    @Override
    public void onBindViewHolder(@NonNull DealViewHolder holder, int position) {
        TravelDeal deal = deals.get(position);
       holder.bind(deal);
    }

    @Override
    public int getItemCount() {
        return deals.size();
    }


    //to describe how to bind the data to a single row
    public class DealViewHolder extends RecyclerView.ViewHolder {

        TextView tvRows;
         public DealViewHolder(@NonNull View itemView) {
            super(itemView);
            tvRows = itemView.findViewById(R.id.txtDealTitle);
        }


        public void bind(TravelDeal deal){
             tvRows.setText(deal.getTitle());
        }
    }
}
